// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LAPEinnahmeAusgabeRechner.Models;
using LAPEinnahmeAusgabeRechner.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LAPEinnahmeAusgabeRechner.Models.Configurations
{
    public partial class EinnahmeConfiguration : IEntityTypeConfiguration<Einnahme>
    {
        public void Configure(EntityTypeBuilder<Einnahme> entity)
        {
            entity.ToTable("EINNAHME", tb =>
                {
                    tb.HasTrigger("TRG_BI_EINNAHME");
                    tb.HasTrigger("TRG_BU_EINNAHME");
                });

            entity.Property(e => e.Valid).HasDefaultValue((short)1);

            entity.HasOne(d => d.Kategorie).WithMany(p => p.Einnahme)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EINNAHME_KATEGORIE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Einnahme> entity);
    }
}
