// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LAPEinnahmeAusgabeRechner.Models.dboSchema
{
    public partial class AusgabeInsertResult
    {
        [Column("AUSGABEID", TypeName = "decimal(38,0)")]
        public decimal? AUSGABEID { get; set; }
    }
}
